### ISSUE TITLE
Convolution perf notes

### ISSUE THREAD

**Issue by jamienoss** [jamienoss/astropy#2]
## Perf boosts

 - [x] #3 NaN treatment
 - [x] #4 Kernel normalization treatment
 - [x] Investigate Cython routines for uneccessary persisting python (code that does __NOT__ generate C).
 _c.f._ [generated Cyhton inspection](http://nealhughes.net/cython1/) (E.g. `cython file.pyx -a`)
 - [x] #6 Investigate possible mem leaks as indicated from #1 results.
 - [x] #5 Python vs C division, the GIL, and DASK
 - [x] #7 manually hoist computations
 - [ ] look into [this](https://github.com/astropy/astropy/blob/master/astropy/convolution/convolve.py#L186-L200). 
 - [x] #9 Direct C investigation
## Other Issues

 - [x] convolve() param `boundary` has default `'fill'` whilst doc states default is `None`. Since the default for `fill_value = 0.` the two are effectively the same. However, if the user accidentally changes the `fill_value` this value will be used as `boundary=None` is __NOT__ the actual default and the internal routine `convolve<N>d_boundary_fill()`  is called and not `convolve<N>d _boundary_none()`. _c.f._ #10
 - [ ] The doc for `convolve()` states that an exception will be raised for `nan_treatment='interpolate'` if the kernel sums to zero and therefore cannot be normalized. This is not actually true, no exception is raised. _Note: not yet tested, code inspection only._

**Comment by jamienoss** [comment]
_Note to self:_ with all perf changes implemented for `boundary=None` and with a 10kx10k image (no `NaN`s present) and 111x111 kernel, the new runtime is ~18min compared to ~25, that's ~40% faster! 
All other defaults were used, i.e. `nan_treatment='interpolate'` and `normalize_kernel=True`.

With a single `NaN` present, the runtimes are pretty much the same. Only a small 4.4% speed up, which may be within the noise (only ran once at this point).

The 40% is still true when `NaN` present but `nan_treatment='fill'`.

**Comment by jamienoss** [comment]
_NB:_ look into [this](https://github.com/astropy/astropy/blob/master/astropy/convolution/convolve.py#L186-L200).
